[colors.primary]
background = "0x100f13"
foreground = "0xf0dcdc"

[colors.normal]
black   = "0x585858"
red     = "0xe04545"
green   = "0x75a850"
yellow  = "0xee9a4d"
blue    = "0x2f77c1"
magenta = "0x9d33bd"
cyan    = "0x37b1c9"
white   = "0xf0dcdc"

[colors.bright]
black   = "0x848484"
red     = "0xe27b7b"
green   = "0xa8cf8b"
yellow  = "0xe1b287"
blue    = "0x6d99c6"
magenta = "0xb863d2"
cyan    = "0x6dc5d6"
white   = "0xc8bfbf"

[font]
size = 10.0

[font.bold]
family = "IosevkaNerdFont"
style = "ExtraBold"

[font.bold_italic]
family = "IosevkaNerdFont"
style = "ExtraBold Italic"

[font.italic]
family = "IosevkaNerdFont"
style = "Italic"

[font.normal]
family = "IosevkaNerdFont"
style = "Regular"
