[colors.primary]
background = "0x232326"
foreground = "0xa7aab0"

[colors.normal]
black   = "0x5a5b5e"
red     = "0xdc5c5c"
green   = "0x8fb573"
yellow  = "0xd9d570"
blue    = "0x56a4e2"
magenta = "0xbb70d2"
cyan    = "0x20b9e5"
white   = "0xa7aab0"

[colors.bright]
black   = "0x777a84"
red     = "0xf08c8c"
green   = "0xb4db98"
yellow  = "0xf7d694"
blue    = "0x8dc7f4"
magenta = "0xd997ed"
cyan    = "0x8ddaf0"
white   = "0x858991"

[font]
size = 10.0

[font.bold]
family = "IosevkaNerdFont"
style = "ExtraBold"

[font.bold_italic]
family = "IosevkaNerdFont"
style = "ExtraBold Italic"

[font.italic]
family = "IosevkaNerdFont"
style = "Italic"

[font.normal]
family = "IosevkaNerdFont"
style = "Regular"
